name: .NET

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

#pull_request:
#branches: [ "main" ]

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
      echo 'Reason: ${{ github.event.inputs.reason }}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
      dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build —no-restore
    - name: Test
      run: dotnet test —no-build —verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - uses: actions/checkout@master
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./SpaceBattle.lib.Test\TestResults\
        flags: unittests, integration
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true

